name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
